# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160808_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='user',
        ),
    ]
