# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Post date'),
        ),
    ]
