# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 16:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(max_length=400, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Imagen Principal'),
        ),
    ]
