# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160809_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='content',
            new_name='content_es',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='intro_es',
        ),
    ]
