# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160809_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='content_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content_pt',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_en',
            field=models.TextField(blank=True, max_length=400, verbose_name='Intro (English)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_pt',
            field=models.TextField(blank=True, max_length=400, verbose_name='Intro (Portuguese)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content_es',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro_es',
            field=models.TextField(max_length=400, verbose_name='Intro (Spanish)'),
        ),
    ]
