# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(max_length=255, verbose_name='Introducción'),
        ),
    ]
