# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160809_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intro',
            new_name='intro_es',
        ),
    ]
