# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160810_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Introduction (English)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_pt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Introduction (Portuguese)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_es',
            field=models.CharField(max_length=255, verbose_name='Introduction (Spanish)'),
        ),
    ]
